name: "ci-dc"

on: 
  push:
    branches:
      - dev
      - main

jobs:
  tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
        - run: npm install
        - run: npm run test:ci
  deploy:
      runs-on: ubuntu-latest
      steps:
        - run: echo github.ref
        - name: "deploy dev"
          if : ${{github.ref}} == "refs/heads/dev"
          run: echo "🚀 Deploying to DEVELOPMENT environment"
        - name: "deploy prod"
          if : ${{github.ref}}== "refs/heads/main"
          run: echo "🚀 Deploying to PRODUCTION environment"

