name: "exo1.5"

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - uses: actions/checkout@v4
      - run: mkdir new_folder
      - run: cd new_folder
      - run: echo "hello world!" > helloWorld.txt
      - run: cd ..
      - run: ls 
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls