name: pizzeria

on: 
  workflow_dispatch:
    inputs:
      nom_client:
        description: "nom du client"
        required: true
      pizzas:
        description: "liste des pizzas commandées"
        required: true

jobs:
  reception_commande:
    name: "Reception de la commande"
    runs-on: ubuntu-latest
    outputs:
      nom_client: ${{ github.event.inputs.nom_client }}
      pizzas: ${{ github.event.inputs.pizzas }}
    steps:
      - id: commande
        name: commande
        run: |
          echo "Bienvenue ${{ github.event.inputs.nom_client }}!"
          echo "Récapitulatif de la commande: ${{ github.event.inputs.pizzas }}"
  cuisine:
    needs: reception_commande
    name: "cuisine"
    strategy:
      matrix:
        pizza: ${{ fromJSON(needs.reception_commande.outputs.pizzas)}}
        taille: ["L", "XL"]
        include:
          - pizza: "pizza dessert gratuite"
            taille: "M"
    runs-on: ubuntu-latest
    steps:
      - id: preparation
        name: preparation
        run: |
          echo "La pizza ${{ matrix.pizza[0]}} est en cours de préparation"
          echo "La pizza ${{ matrix.pizza[1]}} est en cours de préparation"
          echo "La pizza ${{ matrix.pizza[2]}} est en cours de préparation"

