name: pizzeria

on: 
  workflow_dispatch:
    inputs:
      nom_client:
        description: "nom du client"
        required: true
      pizzas:
        description: "liste des pizzas commandées"
        required: true

jobs:
  reception_commande:
    name: "Reception de la commande"
    runs-on: ubuntu-latest
    outputs:
      nom_client: ${{ github.event.inputs.nom_client }}
      pizzas: ${{ github.event.inputs.pizzas }}
    steps:
      - id: commande
        name: commande
        run: |
          echo "Bienvenue ${{ github.event.inputs.nom_client }}!"
          echo "Récapitulatif de la commande: ${{ github.event.inputs.pizzas }}"
  cuisine:
    needs: reception_commande
    name: "cuisine"
    strategy:
      matrix:
        pizza: ${{ fromJSON(needs.reception_commande.outputs.pizzas)}}
        taille: ["L", "XL"]
        include:
          - pizza: "dessert"
            taille: "M"
    runs-on: ubuntu-latest
    steps:
      - id: preparation
        name: preparation
        run: echo "La pizza ${{ matrix.pizza }} taille ${{ matrix.taille }} est en cours de préparation"
  livraison:
    needs: [reception_commande, cuisine]
    name: "livraison"
    concurrency:
      group: zone-livraison
      cancel-in-progress: true
    runs-on: ubuntu-latest 
    steps:
      - name: préparation de la livraison pour le client
        run: echo "Préparation de la livraison pour ${{ needs.reception_commande.outputs.nom_client }}"
      - name: livraison des pizzas 
        run: echo "Les pizzas à livrer sont ${{ needs.cuisine.outputs.pizza }}"
  reclamation:
    needs: livraison
    name: reclamation
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: creation reclamation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: gh issue create --title "réclamation client" --body "pizzas froides"
      
           

  
      


